name: Code Review by Gemini AI
on:
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: "Get diff of the pull request"
        id: get_diff
        shell: bash
        env:
          PULL_REQUEST_HEAD_REF: "${{ github.event.pull_request.head.ref }}"
          PULL_REQUEST_BASE_REF: "${{ github.event.pull_request.base.ref }}"
        run: |-
          git fetch origin "${{ env.PULL_REQUEST_HEAD_REF }}"
          git fetch origin "${{ env.PULL_REQUEST_BASE_REF }}"
          git checkout "${{ env.PULL_REQUEST_HEAD_REF }}"
          git diff "origin/${{ env.PULL_REQUEST_BASE_REF }}" > "diff.txt"
          {
            echo "pull_request_diff<<EOF";
            cat "diff.txt";
            echo 'EOF';
          } >> $GITHUB_OUTPUT
      - uses: rubensflinco/gemini-code-review-action@1.0.5
        name: "Code Review by Gemini AI"
        id: review
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }}
          github_pull_request_number: ${{ github.event.pull_request.number }}
          git_commit_hash: ${{ github.event.pull_request.head.sha }}
          model: "gemini-2.0-flash"
          pull_request_diff: |-
            ${{ steps.get_diff.outputs.pull_request_diff }}
          pull_request_chunk_size: "3500"
          extra_prompt: >-
            You are an expert code reviewer. Your task is to review the provided code changes in the pull request and provide a detailed analysis. Focus on the following aspects:
            **Summary:**
            _Provide a brief summary of your review and the overall quality of the code._

            *ignore .github/workflows/*

            **Code Quality:**

            **Detected Bugs:**
            - List any potential bugs or logical errors.

            **Style Violations (PEP 8):**
            - Note any issues that don't align with the [Python Style Guide (PEP 8)](https://peps.python.org/pep-0008/).

            **Suggestions for Improvement:**
            - Suggest possible refactors, optimizations, or improvements.

            **Commendations:**
            - Highlight anything that’s particularly well done or shows best practice.

            **Overall Verdict:**
            _Approved, Needs Changes, or Rejected.

          max_tokens: "500"
          log_level: "DEBUG"
