name: Code Review by Gemini AI
on:
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: "Get diff of the pull request"
        id: get_diff
        shell: bash
        env:
          PULL_REQUEST_HEAD_REF: "${{ github.event.pull_request.head.ref }}"
          PULL_REQUEST_BASE_REF: "${{ github.event.pull_request.base.ref }}"
        run: |-
          git fetch origin "${{ env.PULL_REQUEST_HEAD_REF }}"
          git fetch origin "${{ env.PULL_REQUEST_BASE_REF }}"
          git checkout "${{ env.PULL_REQUEST_HEAD_REF }}"
          git diff "origin/${{ env.PULL_REQUEST_BASE_REF }}" > "diff.txt"
          {
            echo "pull_request_diff<<EOF";
            cat "diff.txt";
            echo 'EOF';
          } >> $GITHUB_OUTPUT
      - uses: rubensflinco/gemini-code-review-action@1.0.5
        name: "Code Review by Gemini AI"
        id: review
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }}
          github_pull_request_number: ${{ github.event.pull_request.number }}
          git_commit_hash: ${{ github.event.pull_request.head.sha }}
          model: "gemini-2.0-flash"
          pull_request_diff: |-
            ${{ steps.get_diff.outputs.pull_request_diff }}
          pull_request_chunk_size: "3500"
          extra_prompt: >-
            You are a world-class code reviewer—no, scratch that, you’re an expert senior software developer with more than 10 years of experience whose mission is to review this pull request. If you miss a single bug or overlook a style violation, it’s not just a slap on the wrist—it’s straight to code reviewer jail. Your only ally? The Google JavaScript Style Guide. Your weapon? Ruthless attention to detail. This is your final chance to keep the project (and your freedom) intact. Respond only in markdown, as all official FBI reports must be filed. The future of this repository—and your career—depends on it. using the following review template:
              **Summary:**
                _Provide a brief summary of your review and overall code quality._

              **Detected Bugs:**
              - List any potential bugs or logical errors here.

              **Style Violations:**
              - List any style or formatting issues found, referencing the Google JavaScript Style Guide.

              **Suggestions for Improvement:**
              - Suggest refactors, optimizations, or improvements.

              **Commendations:**
              - Point out anything that’s especially well done.

              **Overall Verdict:**
                _Give a final verdict: Approved, Needs Changes, or Rejected._

              ---

              Remember: If you miss anything important, it’s code reviewer jail for you.
          max_tokens: "1000"
          log_level: "DEBUG"
